# Generated by Django 4.2.6 on 2023-12-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCountry', models.CharField(max_length=52, verbose_name='nombreCountry')),
                ('id_country', models.CharField(max_length=3, unique=True, verbose_name='nombreCountry')),
                ('continent_Country', models.IntegerField(verbose_name='continentCountry')),
                ('region_Country', models.CharField(max_length=20, verbose_name='regionCountry')),
                ('surface_Country', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='countryArea')),
                ('indep_year_country', models.SmallIntegerField(null=True, verbose_name='idepCountry')),
                ('population', models.IntegerField(verbose_name='populationCountry')),
                ('life_expectancy', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='lifeExpectancy')),
                ('GNP', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='GNPCountry')),
                ('GNPold', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='GNPold')),
                ('local_name', models.CharField(max_length=45, verbose_name='countryLocalname')),
                ('goverment', models.CharField(max_length=45, verbose_name='countryGoverment')),
                ('state_head', models.CharField(max_length=60, null=True, verbose_name='countryLeader')),
                ('capital_country', models.IntegerField(null=True, verbose_name='capitalId')),
                ('code2', models.CharField(max_length=2, verbose_name='countryCode2')),
                ('siglaCountry', models.CharField(max_length=2, unique=True, verbose_name='siglaCountry')),
                ('activoCountry', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Nombre Country',
                'verbose_name_plural': 'Nombres Countrys',
                'ordering': ['nombreCountry'],
                'unique_together': {('nombreCountry', 'siglaCountry')},
            },
        ),
    ]
