# Generated by Django 4.2.6 on 2023-12-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countrylanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecountrylanguage', models.CharField(max_length=35, verbose_name='nombrecountrylanguage')),
                ('id_country', models.CharField(max_length=3, unique=True, verbose_name='nombreCountry')),
                ('countrylanguage', models.CharField(max_length=30, verbose_name='countrylanguage')),
                ('isOfficial', models.BooleanField(verbose_name='officialanguage')),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='languagePercentaje')),
                ('siglacountrylanguage', models.CharField(max_length=2, unique=True, verbose_name='siglacountrylanguage')),
                ('activocountrylanguage', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Nombre countrylanguage',
                'verbose_name_plural': 'Nombres countrylanguages',
                'ordering': ['nombrecountrylanguage'],
                'unique_together': {('nombrecountrylanguage', 'siglacountrylanguage')},
            },
        ),
    ]
