# Generated by Django 4.2.6 on 2023-12-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('nombre_city', models.CharField(max_length=35, verbose_name='nombreCity')),
                ('id_country', models.CharField(max_length=3, verbose_name='nombreCountry')),
                ('id_city', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='idCity')),
                ('population_city', models.IntegerField(max_length=11, verbose_name='population')),
                ('district_city', models.CharField(max_length=20, verbose_name='district')),
                ('sigla_city', models.CharField(max_length=2, unique=True, verbose_name='siglaCity')),
                ('activo_city', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Nombre City',
                'verbose_name_plural': 'Nombres Citys',
                'ordering': ['nombre_city'],
                'unique_together': {('nombre_city', 'sigla_city')},
            },
        ),
    ]
